name: Deploy to Ubuntu VPS

on:
  push:
    branches: [ main ]  # Deploy when you push to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Deploy using rsync
        uses: appleboy/rsync-action@master
        with:
          rsync_options: -avzh --delete  # Options for efficient transfer
          source: .                  # The local source directory (your repo)
          destination: madman@coscmcs.cc:/var/www/deadman 
          private_key: ${{ secrets.VPS_SSH_KEY }}  # Reference to the secret below
